### ISSUE TITLE
JACK support

### ISSUE THREAD

**Issue by theGreatWhiteShark** [flathub/org.hydrogenmusic.Hydrogen#33]
Hydrogen via Flathub was reported to have broken JACK audio and MIDI support [1]. I can confirm this locally.

I have read through a couple discussions and it seems that with flatpak it is not possible to have a general JACK support. With Pipewire running on the host it would be possible harness Hydrogen's JACK support using pipewire-jack. But in case an old-fashioned JACK server is running on the host, there is no way to connect to it.

@hfiguiere is this (still) correct?

In this case we should compile Hydrogen without JACK support.

[1] https://linuxmusicians.com/viewtopic.php?t=25861

**Comment by hfiguiere** [comment]
It uses pw-jack. Works fine as it is.

**Comment by theGreatWhiteShark** [comment]
> Works fine as it is.

Well, not really.

``` bash
$ flatpak run org.hydrogenmusic.Hydrogen
```
> Hydrogen 1.2.1 [Jun 12 2023]  [http://www.hydrogen-music.org]
Copyright 2002-2008 Alessandro Cominu
Copyright 2008-2023 The hydrogen development team
Hydrogen comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it under certain conditions. See the file COPYING for details.
(E) JackAudioDriver::init Unknown status with JACK server.
(E) JackAudioDriver::init Unknown status with JACK server.
(E) AudioEngine::createAudioDriver Error code [-1] while initializing audio driver [JACK].
(E) AudioEngine::startAudioDrivers Couldn't start audio driver [JACK], falling back to NullDriver


Hydrogen is not able to connect to the JACK server.

**Comment by hfiguiere** [comment]
that's probably because you don't have pipewire. That's the only way it will work. 

Works out of the box on Fedora.

**Comment by hfiguiere** [comment]
![image](https://github.com/flathub/org.hydrogenmusic.Hydrogen/assets/114441/7c09ccad-0ab4-4998-9372-f99f1f8aa488)

![image](https://github.com/flathub/org.hydrogenmusic.Hydrogen/assets/114441/178c03dd-7665-4ab0-b7e4-eea3925d2e73)

**Comment by theGreatWhiteShark** [comment]
> that's probably because you don't have pipewire.

That is right. It is because I'm using JACK, not pipewire. Pipewire is probably working fine but the JACK support is broken from within flatpak. I doubt that there is a non-hacky way to determine whether Hydrogen is running as flatpak and on a pipewire/JACK host in order to turn JACK support on/off during runtime.

The way it is right now all JACK users find JACK support broken within Hydrogen. In my opinion this is very bad and outweighs working JACK support for the subset of pipewire users by a margin. Therefore I suggest to compile it without Hydrogen until pipewire is stable enough and adopted by most distributions
