### ISSUE TITLE
LADSPA support

### ISSUE THREAD

**Issue by theGreatWhiteShark** [flathub/org.hydrogenmusic.Hydrogen#34]
From what I got from all the JACK discussions one can only load shared libraries within flatpak if they were compiled with the same SDK used to build the flatpak itself, right? Therefore not seeing any LADSPA plugins installed on my system should be the expected behavior. But having a large set would definitely be nice.

Do you have a policy for how to handle plugins in flatpak? Maybe something similar to the shared-modules/linux-audio repo but with a large set of plugins that can be added as modules and integrated. Or would this take a too heavy toll on the building system?

**Comment by hfiguiere** [comment]
There are 44 plugin package on flathub. 

For the LADSPA plugins:

```
flatpak search LinuxAudio |grep LADSPA |cut -f 1 |uniq
```

That make 8 packages.

**Comment by theGreatWhiteShark** [comment]
I just tried to add some plugins to the Hydrogen build. But the recipes of plugin modules, like the [LSP one](https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP/blob/branch/19.08/org.freedesktop.LinuxAudio.Plugins.LSP.json), are fully-fledged ones in contrast to the stubs used within the [shared modules](https://github.com/flathub/shared-modules/blob/447d86f87fac03e3933bf266d438741925f1b00c/linux-audio/fluidsynth2.json).

They can not be integrated directly - some even use a different SDK - and patching as well as maintaining the recipes is definitely out of scope.

**Comment by hfiguiere** [comment]
not ure what you were trying to do here. "add some plugins to the Hydrogen build" is not the way. Just install the corresponding flatpak. 

For example:
`flatpak install org.freedesktop.LinuxAudio.Plugins.LSP//22.08`

**Comment by theGreatWhiteShark** [comment]
Oh. This took me by surprise. From reading the docs I thought flatpak is putting all apps into sandboxes not just a single one for all of them (especially when different runtimes are used).  But I can confirm just installing the plugin works and makes it available for Hydrogen.

**Comment by hfiguiere** [comment]
these are not apps. they are extensions. it's designed exactly for that (around a system that didnt have a N:M mapping for extensions)

Any `org.freedesktop.LinuxAudio.Plugins` is an audio plugin. Supported format are VST, VST3, DSSI, LADSPA, LV2 and CLAP. And whenever possible all the format are built.
