### ISSUE TITLE
Add a short note about "JACK" support to the description on flathub

### ISSUE THREAD

**Issue by goebbe** [flathub/org.hydrogenmusic.Hydrogen#38]
Thanks for providing the flatpak build of Hydrogen! 

I have bee filling an enhancement request to Hydrogen, since the Hydrogen build on flathub has not been marked as "verified": 
[Verify hydogen on flathub](https://github.com/hydrogen-music/hydrogen/issues/1974#issuecomment-2111091756)

At this occasion, I learned that Hydrogen-teams considers "JACK" support as an essential prerequisite - and _direct_ support of "JACK" cannot easily be provided using flatpaks.  Therefore, they do not currently recommend or publish flatpaks of Hydrogen. 
I understand, that pipewire may solve this issue in the future in most distributions - but we are not there, yet. 

I would like to suggest clarifying the situation in the **description of Hydrogen on Flathub**, adding the following line (or something similar): 

"This package does not support JACK sound-server directly. See Hydrogen webpage for recommended means of installation. "

By the way, I am grateful for the flatpak version. It allowed me to easily install the latest version of Hydrogen and play around with it on LinuxMint. I have been using classical PulseAudio - which worked well for me (but may be insufficient for more advanced users).

**Comment by hfiguiere** [comment]
It's a Linux Mint problem.

**Comment by goebbe** [comment]
Sorry - but this is not an issue of a specific distribution. 
Nowadays, most distributions could easily be configured to use JACK+pipewire+pipewire-jack (the requirement to access JACK from flatpaks). However, to my knowledge, JACK is only the default in few distributions, that are specialized for audio/ media production. 
Since JACK is seen as a necessary dependency by the developers of Hydrogen, there should at least be a hint to it in the description.  Perhaps something like: 
"**For a professional low latency audio experience, consider installing the JACK audio server alongside Hydrogen**" 

Anyway, thanks for providing the flatpak package of Hydrogen!

**Comment by hfiguiere** [comment]
> Sorry - but this is not an issue of a specific distribution.

It remain a distribution issue. There is nothing we can do to fix Mint. Or Ubuntu. Or whatever.

**Comment by goebbe** [comment]
Thank you for your time answering. 
Every large distribution can relatively easily be configured as required (Fedora, Ubuntu, Arch, Mint ... you name it).
My suggestion was about adding a hint, that typically some configuration is necessary, for **best** results.  (e.g. setting up JACK which is not standard in most distribution)
This seems to be the point of view of the developers of Hydrogen (upstream), who suggested opening this issue, here. 

I always took it as one of the selling points for flatpak, that the builds are largely distribution agnostic (and sandboxing, of course) :-)

Anyway - points of view have been exchanged - back to other things.
